### ISSUE TITLE
UI Mock up for the MZ gadget

### ISSUE THREAD

**Issue by Wissam-Halimi** [react-epfl/gadget#358]
According to previous discussions, we need to change the UI of the MZ to take into consideration the following:
1. the UI should be responsive
2. the UI should have the same look and feel as the previous series of MZ widgets 
3. there are 2 video feeds, we need to find the best placement for them on the UI
4. the graph displaying signal acquired from the photodiode needs to show an output similar to the one we can see on an oscilloscope. The solution is 2 folds:
  a. Acquire enough data points and send them over the websocket. (in progress by me ) 
  b. receive and display UI side (Hagop)
  
There is a google doc with a list of tasks that need to be completed in order to have the experiment ready: https://docs.google.com/spreadsheets/d/1f7To9jODx4O9vIygF0grFBGMjGNmukDAg_Thmftqn74/edit

@hagopj13 i suggest that you do a mockup of the UI before starting the implementation. We can discuss once it's ready.

@dgillet @aholzer if there are any suggestions please let us know

**Comment by hagopj13** [comment]
As of now, points 1 and 2 (mentioned above) have been completed. The following is a list of modifications suggested by the teacher:
1) Make the gadget 2 tabs:
(i) Experiment 1 (etude qualitative): which has the interactive diagram covering the whole width of the page. Under the diagram, there are the 2 video feeds next to each other, each covering 50% of the width of the page (camera 1 showing the experimental setup in infrared mode, and camera 2 showing the rays that are displayed on the screen).
(ii) Experiment 2 (etude quantitative): which has the same divisions and components as experiment 1, except for replacing camera 1 by a graph.

2) Change the location of beamshutter2 to make it occupy the lower side of the diagram (opposite to beamshutter 1 according to its new location)

3) Add camera icons on the diagram at places that represent their actual locations in the experimental setup. Clicking on these icons would turn on/off the respective cameras (Turning off would result in a black background).

4) Push the mirror and the beam splitter that are on the right slightly to the left, to make room for a diverging lens icon next to the screen. This lens will split each incoming wave into a triangular beam that is visualised on the screen. (The screen also needs to be displayed by a thin rectangle).

5) Display the rays in green instead of grey.

6) Make the piezo slider send the current actual voltage and not the triangular wave Vpp. This will allow the student to manually decide the location of the piezo. The respective triangular beam should move with the motion of the mirror.

7) Add a photodetector behind the screen and make it receive one part of the beam (the part that passes through the hole). Also, display a temporary sign (arrow possibly) to show that a photodetector has been added.

**Comment by hagopj13** [comment]
Changes suggested by Adrian:

1) Remove the laser on button, and just replace it with a small white circle on the right side of the blue box. Clicking on the box will result in changing the colour of the small circle to green.

2) Make anything that is clickable dark blue. (For the piezo, make the slider handle dark blue, and the selected part pink (same colour as the mirrors).

3) When the light is off there is a grey path. Whenever the light is turned on this path gets a green colour.

4) Put the piezo slider next to piezo as an attempt to make the diagram shorter.
